package com.soulariamod.init;
import com.soulariamod.CheminSoularia;
import com.soulariamod.ModSoularia;
import com.soulariamod.item.ItemFauxDouteuse;
import com.soulariamod.item.ItemMultiToolP;
import com.soulariamod.item.ItemTutoAxe;
import com.soulariamod.item.ItemTutoHoe;
import com.soulariamod.item.ItemTutoPickaxe;
import com.soulariamod.item.ItemTutoShovel;
import com.soulariamod.item.ItemTutoSword;
import com.soulariamod.tems.EspritHeal;
import com.soulariamod.tems.ItemsMods;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemSword;
import net.minecraftforge.common.util.EnumHelper;

public class ItemMod 
{
	public static ToolMaterial toolRuby = EnumHelper.addToolMaterial("toolRuby", 3, 3500, 14.0F, 4.0F, 15);
	public static ToolMaterial tooldouteux = EnumHelper.addToolMaterial("toolDouteux", 8, 3000, 18.0F, 8.5F, 30);
	public static ToolMaterial toolCobalt = EnumHelper.addToolMaterial("toolCobalt", 4, 3750, 15.0F, 5.0F, 15);
	public static ToolMaterial toolJade = EnumHelper.addToolMaterial("toolJade", 5, 4000, 16.0F, 6.0F, 20);
	public static ToolMaterial toolEnfer = EnumHelper.addToolMaterial("toolEnfer", 6, 4500, 17.5F, 7.0F, 23);
	public static ToolMaterial toolSoularium = EnumHelper.addToolMaterial("toolSoularium", 7, 5000, 20F, 8.0F, 35);
	public static ArmorMaterial armorRuby = EnumHelper.addArmorMaterial("armorRuby", 35, new int[] {6, 10, 8, 5}, 15);
	public static ArmorMaterial armorCobalt = EnumHelper.addArmorMaterial("armorCobalt", 39, new int[] {7, 11, 9, 6}, 20);
	public static ArmorMaterial armorJade = EnumHelper.addArmorMaterial("armorJade", 42, new int[] {8, 12, 10, 7}, 25);
	public static ArmorMaterial armorEnfer = EnumHelper.addArmorMaterial("armorEnfer", 50, new int[] {9, 13, 11, 8}, 30);
	public static ArmorMaterial armorSoularium = EnumHelper.addArmorMaterial("armorSoularium", 50, new int[] {10, 14, 12, 9}, 35);
	
	public static Item item_ruby;
	public static Item espritfireresist, espritspeed, espritforce, espritregen;
	public static Item swordRuby, pickaxeRuby, axeRuby, shovelRuby, hoeRuby, helmetRuby, chestPlateRuby, leggingsRuby, bootsRuby, multiToolRuby;
	public static Item item_cobalt;
	public static Item swordCobalt, pickaxeCobalt, axeCobalt, shovelCobalt, hoeCobalt, helmetCobalt, chestPlateCobalt, leggingsCobalt, bootsCobalt, multiToolCobalt;
	public static Item item_jade;
	public static Item swordJade, pickaxeJade, axeJade, shovelJade, hoeJade, helmetJade, chestPlateJade, leggingsJade, bootsJade, multiToolJade;
	public static Item item_enfer;
	public static Item swordEnfer, pickaxeEnfer, axeEnfer, shovelEnfer, hoeEnfer, helmetEnfer, chestPlateEnfer, leggingsEnfer, bootsEnfer, multiToolEnfer;
	public static Item item_soularium, helmetsoularium, chestPlatesoularium, leggingssoularium, bootssoularium, item_fragmentsoularium, sticksoularium, sabersoularium;
	public static Item item_supreme;
	public static Item clefcobalt, clefjade, clefenfer;
	public static Item dynamite;
	public static Item sceptreheal;
	public static Item fauxdouteuse;
	
	public static void init()
	{
		espritforce = new ItemFoodP(0, 0.0F, false).setAlwaysEdible().setUnlocalizedName("espritforce").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":espritforce");
		sceptreheal = new SceptreHeal().setUnlocalizedName("sceptreheal").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID + ":sceptreheal");
		dynamite = new dynamite().setUnlocalizedName("dynamite").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID + ":dynamite");
		espritspeed = new ItemFoodPI(0, 0.0F, false).setAlwaysEdible().setUnlocalizedName("espritspeed").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":espritspeed");
		clefcobalt = new Item().setUnlocalizedName("clefcobalt").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":clefcobalt");
		item_fragmentsoularium = new Item().setUnlocalizedName("fragmentsoularium").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":fragmentsoularium");
		sticksoularium = new Item().setUnlocalizedName("sticksoularium").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":sticksoularium");
		clefjade = new Item().setUnlocalizedName("clefjade").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":clefjade");
		clefenfer = new Item().setUnlocalizedName("clefenfer").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":clefenfer");
		espritfireresist = new ItemFoodPII(0, 0.0F, false).setAlwaysEdible().setUnlocalizedName("espritfireresist").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":espritfireresist");
		espritregen = new ItemFoodPIII(0, 0.0F, false).setAlwaysEdible().setUnlocalizedName("espritregen").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":espritregen");
		item_ruby = new Item().setUnlocalizedName("Ruby").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":ruby");
        swordRuby = new ItemTutoSword(toolRuby).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("swordRuby").setTextureName(CheminSoularia.MOD_ID + ":sword_ruby");
        pickaxeRuby = new ItemTutoPickaxe(toolRuby).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("pickaxeRuby").setTextureName(CheminSoularia.MOD_ID + ":pickaxe_ruby");
        axeRuby = new ItemTutoAxe(toolRuby).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("axeRuby").setTextureName(CheminSoularia.MOD_ID + ":axe_ruby");
        shovelRuby = new ItemTutoShovel(toolRuby).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("shovelRuby").setTextureName(CheminSoularia.MOD_ID + ":shovel_ruby");
        hoeRuby = new ItemTutoHoe(toolRuby).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("hoeRuby").setTextureName(CheminSoularia.MOD_ID + ":hoe_ruby");
        swordCobalt = new ItemTutoSword(toolCobalt).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("swordCobalt").setTextureName(CheminSoularia.MOD_ID + ":sword_cobalt");
        pickaxeCobalt = new ItemTutoPickaxe(toolCobalt).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("pickaxeCobalt").setTextureName(CheminSoularia.MOD_ID + ":pickaxe_cobalt");
        axeCobalt = new ItemTutoAxe(toolCobalt).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("axeCobalt").setTextureName(CheminSoularia.MOD_ID + ":axe_cobalt");
        shovelCobalt = new ItemTutoShovel(toolCobalt).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("shovelCobalt").setTextureName(CheminSoularia.MOD_ID + ":shovel_cobalt");
        hoeCobalt = new ItemTutoHoe(toolCobalt).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("hoeCobalt").setTextureName(CheminSoularia.MOD_ID + ":hoe_cobalt");
        swordJade = new ItemTutoSword(toolJade).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("swordJade").setTextureName(CheminSoularia.MOD_ID + ":sword_jade");
        pickaxeJade = new ItemTutoPickaxe(toolJade).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("pickaxeJade").setTextureName(CheminSoularia.MOD_ID + ":pickaxe_jade");
        axeJade = new ItemTutoAxe(toolJade).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("axeJade").setTextureName(CheminSoularia.MOD_ID + ":axe_jade");
        shovelJade = new ItemTutoShovel(toolJade).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("shovelJade").setTextureName(CheminSoularia.MOD_ID + ":shovel_jade");
        hoeJade = new ItemTutoHoe(toolJade).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("hoeJade").setTextureName(CheminSoularia.MOD_ID + ":hoe_jade");
        swordEnfer = new ItemTutoSword(toolEnfer).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("swordEnfer").setTextureName(CheminSoularia.MOD_ID + ":sword_enfer");
        pickaxeEnfer = new ItemTutoPickaxe(toolEnfer).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("pickaxeEnfer").setTextureName(CheminSoularia.MOD_ID + ":pickaxe_enfer");
        axeEnfer = new ItemTutoAxe(toolEnfer).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("axeEnfer").setTextureName(CheminSoularia.MOD_ID + ":axe_enfer");
        shovelEnfer = new ItemTutoShovel(toolEnfer).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("shovelEnfer").setTextureName(CheminSoularia.MOD_ID + ":shovel_enfer");
        hoeEnfer = new ItemTutoHoe(toolEnfer).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("hoeEnfer").setTextureName(CheminSoularia.MOD_ID + ":hoe_enfer");
		item_cobalt = new Item().setUnlocalizedName("Cobalt").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":cobalt");
		item_jade = new Item().setUnlocalizedName("Jade").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":jade");
		item_enfer = new Item().setUnlocalizedName("Enfer").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":enfer");
		item_soularium = new Item().setUnlocalizedName("Soularium").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":soularium");
		item_supreme = new Item().setUnlocalizedName("Supreme").setCreativeTab(ModSoularia.tabSoularia).setTextureName(CheminSoularia.MOD_ID +":supreme");
        helmetRuby = new ItemPArmor(armorRuby, 0).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("helmetRuby").setTextureName(CheminSoularia.MOD_ID + ":helmet_ruby");
        chestPlateRuby = new ItemPArmor(armorRuby, 1).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("chestPlateRuby").setTextureName(CheminSoularia.MOD_ID + ":chestplate_ruby");
        leggingsRuby = new ItemPArmor(armorRuby, 2).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("leggingsRuby").setTextureName(CheminSoularia.MOD_ID + ":leggings_ruby");
        bootsRuby = new ItemPArmor(armorRuby, 3).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("bootsRuby").setTextureName(CheminSoularia.MOD_ID + ":boots_ruby");
        helmetCobalt = new ItemPArmor(armorCobalt, 0).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("helmetCobalt").setTextureName(CheminSoularia.MOD_ID + ":helmet_cobalt");
        chestPlateCobalt = new ItemPArmor(armorCobalt, 1).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("chestPlateCobalt").setTextureName(CheminSoularia.MOD_ID + ":chestplate_cobalt");
        leggingsCobalt = new ItemPArmor(armorCobalt, 2).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("leggingsCobalt").setTextureName(CheminSoularia.MOD_ID + ":leggings_cobalt");
        bootsCobalt = new ItemPArmor(armorCobalt, 3).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("bootsCobalt").setTextureName(CheminSoularia.MOD_ID + ":boots_cobalt");
        helmetJade = new ItemPArmor(armorJade, 0).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("helmetJade").setTextureName(CheminSoularia.MOD_ID + ":helmet_jade");
        chestPlateJade = new ItemPArmor(armorJade, 1).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("chestPlateJade").setTextureName(CheminSoularia.MOD_ID + ":chestplate_jade");
        leggingsJade = new ItemPArmor(armorJade, 2).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("leggingsJade").setTextureName(CheminSoularia.MOD_ID + ":leggings_jade");
        bootsJade = new ItemPArmor(armorJade, 3).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("bootsJade").setTextureName(CheminSoularia.MOD_ID + ":boots_jade");
        helmetEnfer = new ItemPArmor(armorJade, 0).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("helmetEnfer").setTextureName(CheminSoularia.MOD_ID + ":helmet_enfer");
        chestPlateEnfer = new ItemPArmor(armorEnfer, 1).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("chestPlateEnfer").setTextureName(CheminSoularia.MOD_ID + ":chestplate_enfer");
        leggingsEnfer = new ItemPArmor(armorEnfer, 2).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("leggingsEnfer").setTextureName(CheminSoularia.MOD_ID + ":leggings_enfer");
        bootsEnfer = new ItemPArmor(armorEnfer, 3).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("bootsEnfer").setTextureName(CheminSoularia.MOD_ID + ":boots_enfer");
        helmetsoularium = new ItemPArmor(armorSoularium, 0).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("helmetSoularium").setTextureName(CheminSoularia.MOD_ID + ":helmet_soularium");
        chestPlatesoularium = new ItemPArmor(armorSoularium, 1).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("chestPlateSoularium").setTextureName(CheminSoularia.MOD_ID + ":chestplate_soularium");
        leggingssoularium = new ItemPArmor(armorSoularium, 2).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("leggingsSoularium").setTextureName(CheminSoularia.MOD_ID + ":leggings_soularium");
        bootssoularium = new ItemPArmor(armorSoularium, 3).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("bootsSoularium").setTextureName(CheminSoularia.MOD_ID + ":boots_soularium");
        multiToolRuby = new ItemMultiToolP(toolRuby).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("multiToolRuby").setTextureName(CheminSoularia.MOD_ID + ":multitool_ruby");
        multiToolCobalt = new ItemMultiToolP(toolCobalt).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("multiToolCobalt").setTextureName(CheminSoularia.MOD_ID + ":multitool_cobalt");
        multiToolJade = new ItemMultiToolP(toolJade).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("multiToolJade").setTextureName(CheminSoularia.MOD_ID + ":multitool_jade");
        multiToolEnfer = new ItemMultiToolP(toolEnfer).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("multiToolEnfer").setTextureName(CheminSoularia.MOD_ID + ":multitool_enfer");
        sabersoularium = new ItemTutoSword(toolSoularium).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("sabersoularium").setTextureName(CheminSoularia.MOD_ID + ":sabersoularium");
        fauxdouteuse = new ItemFauxDouteuse(tooldouteux).setCreativeTab(ModSoularia.tabSoularia).setUnlocalizedName("fauxdouteuse").setTextureName(CheminSoularia.MOD_ID + ":faux_douteuse");
	}
	
	public static void register()
	{
		GameRegistry.registerItem(item_ruby, "Ruby");
		GameRegistry.registerItem(item_cobalt, "Cobalt");
		GameRegistry.registerItem(item_jade, "Jade");
		GameRegistry.registerItem(item_enfer, "Enfer");
		GameRegistry.registerItem(item_soularium, "Soularium");
		GameRegistry.registerItem(item_supreme, "Supreme");
        GameRegistry.registerItem(swordRuby, "item_ruby_sword");
        GameRegistry.registerItem(pickaxeRuby, "item_ruby_pickaxe");
        GameRegistry.registerItem(shovelRuby, "item_ruby_shovel");
        GameRegistry.registerItem(hoeRuby, "item_ruby_hoe");
        GameRegistry.registerItem(hoeCobalt, "item_cobalt_hoe");
        GameRegistry.registerItem(swordCobalt, "item_cobalt_sword");
        GameRegistry.registerItem(axeCobalt, "item_cobalt_axe");
        GameRegistry.registerItem(pickaxeCobalt, "item_cobalt_pickaxe");
        GameRegistry.registerItem(shovelCobalt, "item_cobalt_shovel");
        GameRegistry.registerItem(hoeJade, "item_jade_hoe");
        GameRegistry.registerItem(swordJade, "item_jade_sword");
        GameRegistry.registerItem(axeJade, "item_jade_axe");
        GameRegistry.registerItem(pickaxeJade, "item_jade_pickaxe");
        GameRegistry.registerItem(shovelJade, "item_jade_shovel");
        GameRegistry.registerItem(hoeEnfer, "item_enfer_hoe");
        GameRegistry.registerItem(swordEnfer, "item_enfer_sword");
        GameRegistry.registerItem(axeEnfer, "item_enfer_axe");
        GameRegistry.registerItem(pickaxeEnfer, "item_enfer_pickaxe");
        GameRegistry.registerItem(shovelEnfer, "item_enfer_shovel");
        GameRegistry.registerItem(helmetRuby, "helmetRuby");
        GameRegistry.registerItem(chestPlateRuby, "chestPlateRuby");
        GameRegistry.registerItem(leggingsRuby, "leggingsRuby");
        GameRegistry.registerItem(bootsRuby, "bootsRuby");
        GameRegistry.registerItem(helmetCobalt, "helmetCobalt");
        GameRegistry.registerItem(chestPlateCobalt, "chestPlateCobalt");
        GameRegistry.registerItem(leggingsCobalt, "leggingsCobalt");
        GameRegistry.registerItem(bootsCobalt, "bootsCobalt");
        GameRegistry.registerItem(helmetJade, "helmetJade");
        GameRegistry.registerItem(chestPlateJade, "chestPlateJade");
        GameRegistry.registerItem(leggingsJade, "leggingsJade");
        GameRegistry.registerItem(bootsJade, "bootsJade");
        GameRegistry.registerItem(helmetEnfer, "helmetEnfer");
        GameRegistry.registerItem(chestPlateEnfer, "chestPlateEnfer");
        GameRegistry.registerItem(leggingsEnfer, "leggingsEnfer");
        GameRegistry.registerItem(bootsEnfer, "bootsEnfer");
        GameRegistry.registerItem(multiToolRuby, "multiToolRuby");
        GameRegistry.registerItem(multiToolCobalt, "multiToolCobalt");
        GameRegistry.registerItem(multiToolJade, "multiToolJade");
        GameRegistry.registerItem(multiToolEnfer, "multiToolEnfer");
        GameRegistry.registerItem(espritforce, "espritforce");
        GameRegistry.registerItem(espritspeed, "espritspeed");
        GameRegistry.registerItem(espritfireresist, "espritfireresist");
        GameRegistry.registerItem(espritregen, "espritregen");
        GameRegistry.registerItem(clefcobalt, "clefcobalt");
        GameRegistry.registerItem(clefjade, "clefjade");
        GameRegistry.registerItem(clefenfer, "clefenfer");
        GameRegistry.registerItem(helmetsoularium, "helmetSoularium");
        GameRegistry.registerItem(chestPlatesoularium, "chestPlateSoularium");
        GameRegistry.registerItem(leggingssoularium, "leggingsSoularium");
        GameRegistry.registerItem(bootssoularium, "bootsSoularium");
        GameRegistry.registerItem(dynamite, "dynamite");
        GameRegistry.registerItem(item_fragmentsoularium, "fragmentsoularium");
        GameRegistry.registerItem(sticksoularium, "sticksoularium");
        GameRegistry.registerItem(sceptreheal, "sceptreheal");
        GameRegistry.registerItem(sabersoularium, "sabersoularium");
        GameRegistry.registerItem(fauxdouteuse, "fauxdouteuse");
		GameRegistry.addRecipe(new ItemStack(ItemMod.swordRuby, 1), new Object[]{" = ", " = ", " f ", '=', ItemMod.item_ruby, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.pickaxeRuby, 1), new Object[]{"===", " f ", " f ", '=', ItemMod.item_ruby, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.shovelRuby, 1), new Object[]{" = ", " f ", " f ", '=', ItemMod.item_ruby, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.hoeRuby, 1), new Object[]{"== ", " f ", " f ", '=', ItemMod.item_ruby, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.swordCobalt, 1), new Object[]{" = ", " = ", " f ", '=', ItemMod.item_cobalt, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.pickaxeCobalt, 1), new Object[]{"===", " f ", " f ", '=', ItemMod.item_cobalt, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.shovelCobalt, 1), new Object[]{" = ", " f ", " f ", '=', ItemMod.item_cobalt, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.axeCobalt, 1), new Object[]{"== ", "=f ", " f ", '=', ItemMod.item_cobalt, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.hoeCobalt, 1), new Object[]{"== ", " f ", " f ", '=', ItemMod.item_cobalt, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.swordJade, 1), new Object[]{" = ", " = ", " f ", '=', ItemMod.item_jade, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.pickaxeJade, 1), new Object[]{"===", " f ", " f ", '=', ItemMod.item_jade, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.shovelJade, 1), new Object[]{" = ", " f ", " f ", '=', ItemMod.item_jade, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.axeJade, 1), new Object[]{"== ", "=f ", " f ", '=', ItemMod.item_jade, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.hoeJade, 1), new Object[]{"== ", " f ", " f ", '=', ItemMod.item_jade, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.swordEnfer, 1), new Object[]{" = ", " = ", " f ", '=', ItemMod.item_enfer, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.pickaxeEnfer, 1), new Object[]{"===", " f ", " f ", '=', ItemMod.item_enfer, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.shovelEnfer, 1), new Object[]{" = ", " f ", " f ", '=', ItemMod.item_enfer, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.axeEnfer, 1), new Object[]{"== ", "=f ", " f ", '=', ItemMod.item_enfer, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.hoeEnfer, 1), new Object[]{"== ", " f ", " f ", '=', ItemMod.item_enfer, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.helmetRuby, 1), new Object[]{"===", "= =", "   ", '=', ItemMod.item_ruby});
		GameRegistry.addRecipe(new ItemStack(ItemMod.chestPlateRuby, 1), new Object[]{"= =", "===", "===", '=', ItemMod.item_ruby});
		GameRegistry.addRecipe(new ItemStack(ItemMod.leggingsRuby, 1), new Object[]{"===", "= =", "= =", '=', ItemMod.item_ruby});
		GameRegistry.addRecipe(new ItemStack(ItemMod.bootsRuby, 1), new Object[]{"   ", "= =", "= =", '=', ItemMod.item_ruby});
		GameRegistry.addRecipe(new ItemStack(ItemMod.helmetCobalt, 1), new Object[]{"===", "= =", "   ", '=', ItemMod.item_cobalt});
		GameRegistry.addRecipe(new ItemStack(ItemMod.chestPlateCobalt, 1), new Object[]{"= =", "===", "===", '=', ItemMod.item_cobalt});
		GameRegistry.addRecipe(new ItemStack(ItemMod.leggingsCobalt, 1), new Object[]{"===", "= =", "= =", '=', ItemMod.item_cobalt});
		GameRegistry.addRecipe(new ItemStack(ItemMod.bootsCobalt, 1), new Object[]{"   ", "= =", "= =", '=', ItemMod.item_cobalt});
		GameRegistry.addRecipe(new ItemStack(ItemMod.helmetJade, 1), new Object[]{"===", "= =", "   ", '=', ItemMod.item_jade});
		GameRegistry.addRecipe(new ItemStack(ItemMod.chestPlateJade, 1), new Object[]{"= =", "===", "===", '=', ItemMod.item_jade});
		GameRegistry.addRecipe(new ItemStack(ItemMod.leggingsJade, 1), new Object[]{"===", "= =", "= =", '=', ItemMod.item_jade});
		GameRegistry.addRecipe(new ItemStack(ItemMod.bootsJade, 1), new Object[]{"   ", "= =", "= =", '=', ItemMod.item_jade});
		GameRegistry.addRecipe(new ItemStack(ItemMod.helmetEnfer, 1), new Object[]{"===", "= =", "   ", '=', ItemMod.item_enfer});
		GameRegistry.addRecipe(new ItemStack(ItemMod.chestPlateEnfer, 1), new Object[]{"= =", "===", "===", '=', ItemMod.item_enfer});
		GameRegistry.addRecipe(new ItemStack(ItemMod.leggingsEnfer, 1), new Object[]{"===", "= =", "= =", '=', ItemMod.item_enfer});
		GameRegistry.addRecipe(new ItemStack(ItemMod.bootsEnfer, 1), new Object[]{"   ", "= =", "= =", '=', ItemMod.item_enfer});
		GameRegistry.addRecipe(new ItemStack(ItemMod.multiToolRuby, 1), new Object[]{"===", "=f ", " f ", '=', ItemMod.item_ruby, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.multiToolCobalt, 1), new Object[]{"===", "=f ", " f ", '=', ItemMod.item_cobalt, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.multiToolEnfer, 1), new Object[]{"===", "=f ", " f ", '=', ItemMod.item_enfer, 'f', Items.stick});
		GameRegistry.addRecipe(new ItemStack(ItemMod.helmetsoularium, 1), new Object[]{"===", "= =", "   ", '=', ItemMod.item_soularium});
		GameRegistry.addRecipe(new ItemStack(ItemMod.chestPlatesoularium, 1), new Object[]{"= =", "===", "===", '=', ItemMod.item_soularium});
		GameRegistry.addRecipe(new ItemStack(ItemMod.leggingssoularium, 1), new Object[]{"===", "= =", "= =", '=', ItemMod.item_soularium});
		GameRegistry.addRecipe(new ItemStack(ItemMod.bootssoularium, 1), new Object[]{"   ", "= =", "= =", '=', ItemMod.item_soularium});
		GameRegistry.addRecipe(new ItemStack(ItemMod.dynamite, 1), new Object[]{"===", "===", "===", '=', Blocks.tnt});
		GameRegistry.addRecipe(new ItemStack(ItemMod.item_soularium, 1), new Object[]{"===", "===", "===", '=', ItemMod.item_fragmentsoularium});
		GameRegistry.addRecipe(new ItemStack(ItemMod.sticksoularium, 1), new Object[]{"   ", " = ", " = ", '=', ItemMod.item_soularium});
		GameRegistry.addRecipe(new ItemStack(ItemMod.sabersoularium, 1), new Object[]{" = ", " = ", " f ", '=', ItemMod.item_soularium, 'f', ItemMod.sticksoularium});
	}
}
